### ISSUE TITLE
When ShouldDisposeStream is set to false, consider resetting the stream position to 0

### ISSUE THREAD

**Issue by superjulius** [clarkis117/Mime-Detective#11]
We found out today that files that were analyzed (using stream extension - GetFileTypeAsync) were corrupted as we had not reset the stream position before saving it as a file.

I would therefore suggest to reset the stream position to 0 in case the stream is not disposed, or at least making it explicit in comments/wiki/docs

**Comment by clarkis117** [comment]
https://github.com/Muraad/Mime-Detective/issues/19

**Comment by clarkis117** [comment]
I think this should be the expected behavior for extension methods, so I'm fine with this breaking change. However, more tests will have to be added around things like network streams which don't allow seeking.
