### ISSUE TITLE
NullReferenceException reading Excel: 0.0.6-alpha1

### ISSUE THREAD

**Issue by 1100594** [clarkis117/Mime-Detective#12]
When detecting a Excel File from a byte array throws a NullReferenceException at MimeDetective.MimeTypes.FindZipType(ReadResult& readResult) in \src\Mime-Detective\MimeTypes.cs:line 314

```

var fileData = File.ReadAllBytes(filePath);
var type = fileData.GetFileType(); 
```
[test.xlsx](https://github.com/clarkis117/Mime-Detective/files/1794055/test.xlsx)

**Comment by clarkis117** [comment]
@1100594 what's the nugget version?

**Comment by 1100594** [comment]
0.0.6-alpha1

**Comment by clarkis117** [comment]
@1100594 Thank you for the report will look into this soon 😀

**Comment by 1100594** [comment]
Thank you @clarkis117,,

I have more information for you.

The problem is that you trying to change the value of a in "readResult" parameter (aka. readonly ref parameter), please consider remove the "in" keyword or use another approach to change the value of the "source" prop.

**More info:** [](https://blogs.msdn.microsoft.com/mazhou/2018/01/08/c-7-series-part-8-in-parameters/)

**Comment by clarkis117** [comment]
Resolved by #13

**Comment by clarkis117** [comment]
@1100594 The new version (alpha2) should be available on nuget now 😁

**Comment by 1100594** [comment]
Great! Thank you @clarkis117!
