### ISSUE TITLE
System.NullReferenceException - 0.0.6 beta 2

### ISSUE THREAD

**Issue by 1100594** [clarkis117/Mime-Detective#18]
Hi @clarkis117,

Sorry for the spam, but I'm having another issue with txt files in the version 0.0.6 beta 2. 

**Exception:**   System.NullReferenceException: 'Object reference not set to an instance of an object.'
MimeDetective.ByteArrayExtensions.GetFileType(...) returned null.

**Use case:** 
`File.ReadAllBytes(filePath).GetFileType()`

**Sample of file:** [test.txt](https://github.com/clarkis117/Mime-Detective/files/1841032/test.txt)

**TargetFramework:** .NET Core 2.0

Thank you,

**Comment by clarkis117** [comment]
This is a difficult issue and will probably require some design at a later point. It’s nearly impossible to guess the correct text encoding between ASCII, Windows-1252, and UTF-8 without a BOM (Byte Order Mark). The library currently only matches text files to UTF-x with a BOM. Therefore, I recommend null checking the results of any suspected text file. Although, I also recommend null checking the results in general as null is used to represent no match.

**Comment by 1100594** [comment]
Ok @clarkis117 I will do that. Thank you for the detailed information!
