### ISSUE TITLE
ToDo Feature: Add Async Support

### ISSUE THREAD

**Issue by clarkis117** [clarkis117/Mime-Detective#2]
open issue for adding TAP based Async Support

**Comment by vincpa** [comment]
Is the API changing at all? If not, which part of the API would benefit from Async support?

**Comment by clarkis117** [comment]
I'm just planning on adding on to the API. The main benefit would be not blocking where the file header is read from the disk.

**Comment by clarkis117** [comment]
Don't mind me, I'm kind of a noob at this and correct me if I'm wrong. I was doing some research, looking at async code samples inside the CLR, Kestrel web server, and the 6 essential async tips videos on Channel 9. The only part of the code that could really benefit from async is where the file header is read from a stream or the file system. This would be IO bound async, so it would be really just forwarding the await where the file data is read. Although, where the data is read from a byte array could be made async through something like Task.Run since it's cpu bound work. Thoughts?
