### ISSUE TITLE
net451 support

### ISSUE THREAD

**Issue by fubar-coder** [clarkis117/Mime-Detective#3]
net451 support would be nice to have, because many companies are still limited to this framework.

**Comment by sandrock** [comment]
It would be even better to support net45 which has almost no difference with net451.

**Comment by clarkis117** [comment]
Gotcha, net45 and net451 support are slated for 0.0.2 and should be up this weekend.

**Comment by clarkis117** [comment]
@fubar-coder @sandrock The only blocker for it should be adding framework assembly references to the project.json file

**Comment by clarkis117** [comment]
@fubar-coder  @sandrock Version 0.0.3 is up on nugget, it supports net4.5 and netstandard 1.3
