### ISSUE TITLE
Throwing exeption when it cannot determine the file type. 

### ISSUE THREAD

**Issue by krlm** [clarkis117/Mime-Detective#4]
Methods which return FileType from (`MimeTypes.cs`) usually have this comment: 
```
	/// <summary>
	/// Read header of a file and depending on the information in the header
	/// return object FileType.
	/// *Return null in case when the file type is not identified.*
	/// Throws Application exception if the file can not be read or does not exist
	/// </summary>
```
But because of that line https://github.com/clarkis117/Mime-Detective/blob/master/src/Mime-Detective/MimeTypes.cs#L314 this statement about return value isn't true.

**Comment by clarkis117** [comment]
This is addressed in 0.0.3,  thanks for raising the issue :)
