### ISSUE TITLE
ZipArchive disposes stream

### ISSUE THREAD

**Issue by marko444** [clarkis117/Mime-Detective#5]
Input stream will be disposed after calling GetFileType().

Regards!

**Comment by clarkis117** [comment]
@marko444 Thanks for raising this issue 😀

**Comment by clarkis117** [comment]
Version 0.0.3 will address this, btw

**Comment by clarkis117** [comment]
Version 0.0.3 addressed this by not allowing stream inputs to be closed and added regression tests for this
