### ISSUE TITLE
Does not work with files under 560 B.

### ISSUE THREAD

**Issue by Bolfur** [clarkis117/Mime-Detective#6]
The MIME type detection crashes (throws an ArgumentException) on files smaller then 560 bytes, e. g. tiny plain text files.

**Comment by clarkis117** [comment]
This will be patched and included for version 0.0.4, and a regression test will be added for it. @Bolfur Thank you for filing an issue, I appreciate it.  👍

**Comment by clarkis117** [comment]
@Bolfur The fix has been committed and the package has been published for the argument exception. However, to completely solve the handling of small text files an encoding detector will have to be added (several byte files one - ~8 bytes).
