### ISSUE TITLE
PDF files detected as plain/text

### ISSUE THREAD

**Issue by superjulius** [clarkis117/Mime-Detective#8]
I faced the same [issue #12](https://github.com/Muraad/Mime-Detective/issues/12) as reported in the original repository.

The proposed change was to run the file signature detection first, and then plain text detection.
That would definitely fix the issue and be more reliable.

Would you consider making this change?

If so, it might then be possible to improve the plain text detection to detect the file encoding.

**Comment by clarkis117** [comment]
@superjulius do you have a sample pdf that replicates this? I wasn't able to replicate it using a pdf generated by Microsoft Print to PDF on Windows 10. Improving handling of plan text files, is on my todo list.

**Comment by superjulius** [comment]
@clarkis117 I unfortunately cannot share the PDF with which I faced the issue but you can definitely used the one referenced (http://www.orimi.com/pdf-test.pdf) in the issue mentioned above.

**Comment by clarkis117** [comment]
@superjulius I was not able to replicate this behavior on my dev branch for 0.6.0; therefore, it seems fixed. Just in case, I'm adding more data tests around pdfs.

**Comment by clarkis117** [comment]
@superjulius  PDF detection should be working properly in this build, please see if you can repro your issue https://ci.appveyor.com/project/clarkis117/mime-detective/build/artifacts

**Comment by superjulius** [comment]
I have been out for couple of weeks and I just tried the file detection which worked great on both the pdf referenced in the issue (i.e. pdf-test.pdf) and the PDF that I could not share. I think that you could close this issue. Thanks for your work!
